
let steamGamesInfo = [
    {
        id: '1',
        name: 'Counter Strike 2',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'FPS',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Valve',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/1/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '2',
        name: 'Baldurs Gate 3',
        priceStatus: {
            is_free: false,
            price: 35,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Singleplayer',
            'Roleplay',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Larian Studios',
        discountStatus: {
            discount_active: true,
            discount_amount: 20,
        },
        imageSmall: '',
        imageHeader: '../images/games/2/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '3',
        name: 'Elden Ring',
        priceStatus: {
            is_free: false,
            price: 48,
        },
        categories: [
            'Adventure',
            'Action',
            'Fighting',
            'Singleplayer',
            'Roleplay',
            'Open world',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'FromSoftware Inc.',
        discountStatus: {
            discount_active: true,
            discount_amount: 30,
        },
        imageSmall: '',
        imageHeader: '../images/games/3/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '4',
        name: 'Team Fortress 2',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'FPS',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Valve',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/4/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '5',
        name: 'PUBG: BATTLEGROUNDS',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'KRAFTON, Inc.',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/5/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '6',
        name: 'Apex Legends',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Respawn',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/6/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '7',
        name: 'Grand Theft Auto V',
        priceStatus: {
            is_free: false,
            price: 30,
        },
        categories: [
            'Adventure',
            'Open world',
            'Singleplayer',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Rockstar North',
        discountStatus: {
            discount_active: true,
            discount_amount: 63,
        },
        imageSmall: '',
        imageHeader: '../images/games/7/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '8',
        name: 'Rust',
        priceStatus: {
            is_free: false,
            price: 19,
        },
        categories: [
            'Action',
            'FPS',
            'Multiplayer',
            'Open world',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Facepunch Studios',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/8/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '9',
        name: 'Stardew Valley',
        priceStatus: {
            is_free: false,
            price: 5,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'ConcernedApe',
        discountStatus: {
            discount_active: true,
            discount_amount: 40,
        },
        imageSmall: '',
        imageHeader: '../images/games/9/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '10',
        name: 'War Thunder',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Free to play',
            'Multiplayer',
            'Simulation',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Gaijin Entertainment',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/10/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '11',
        name: 'Palworld',
        priceStatus: {
            is_free: false,
            price: 15,
        },
        categories: [
            'Adventure',
            'Multiplayer',
            'Open world',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Pocketpair',
        discountStatus: {
            discount_active: true,
            discount_amount: 25,
        },
        imageSmall: '',
        imageHeader: '../images/games/11/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '12',
        name: '7 Days to Die',
        priceStatus: {
            is_free: false,
            price: 25,
        },
        categories: [
            'Action',
            'Co-op',
            'Multiplayer',
            'Horror',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'The Fun Pimps',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/12/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '13',
        name: 'Sid Meiers Civilization VI',
        priceStatus: {
            is_free: false,
            price: 48,
        },
        categories: [
            'Multiplayer',
            'Singleplayer',
            'Turns',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Firaxis Games',
        discountStatus: {
            discount_active: true,
            discount_amount: 95,
        },
        imageSmall: '',
        imageHeader: '../images/games/13/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '15',
        name: 'Wallpaper Engine',
        priceStatus: {
            is_free: false,
            price: 2.80,
        },
        categories: [
            'Software',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Wallpaper Engine Team',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/15/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '16',
        name: 'Dead by Daylight',
        priceStatus: {
            is_free: false,
            price: 15,
        },
        categories: [
            'Arcade',
            'Co-op',
            'Horror',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Behaviour Interactive Inc.',
        discountStatus: {
            discount_active: true,
            discount_amount: 60,
        },
        imageSmall: '',
        imageHeader: '../images/games/16/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '17',
        name: 'DayZ',
        priceStatus: {
            is_free: false,
            price: 50,
        },
        categories: [
            'Action',
            'Horror',
            'Multiplayer',
            'Open world',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Bohemia Interactive',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/17/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '18',
        name: 'The Sims™ 4',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Arcade',
            'Free to play',
            'Simulation',
            'Singleplayer',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'Electronic Arts',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/18/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '19',
        name: 'Dark and Darker',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Arcade',
            'Co-op',
            'Free to play',
            'Multiplayer',
            'Puzzle',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'IRONMACE',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/19/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '20',
        name: 'Euro Truck Simulator 2',
        priceStatus: {
            is_free: false,
            price: 10,
        },
        categories: [
            'Multiplayer',
            'Open world',
            'Simulation',
            'Singleplayer',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'SCS Software',
        discountStatus: {
            discount_active: true,
            discount_amount: 90,
        },
        imageSmall: '',
        imageHeader: '../images/games/20/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '21',
        name: 'Hearts of Iron IV',
        priceStatus: {
            is_free: false,
            price: 30,
        },
        categories: [
            'Multiplayer',
            'RTS',
            'Singleplayer',
            'Turns',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Paradox Development Studio',
        discountStatus: {
            discount_active: true,
            discount_amount: 70,
        },
        imageSmall: '',
        imageHeader: '../images/games/21/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '22',
        name: 'Fallout 4',
        priceStatus: {
            is_free: false,
            price: 12,
        },
        categories: [
            'Open world',
            'Roleplay',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Bethesda Game Studios',
        discountStatus: {
            discount_active: true,
            discount_amount: 60,
        },
        imageSmall: '',
        imageHeader: '../images/games/22/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '23',
        name: 'Helldivers II',
        priceStatus: {
            is_free: false,
            price: 40,
        },
        categories: [
            'Action',
            'Co-op',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Arrowhead Game Studios',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/23/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '24',
        name: 'Valheim',
        priceStatus: {
            is_free: false,
            price: 20,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Open world',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'Iron Gate AB',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/24/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '25',
        name: 'Terraria',
        priceStatus: {
            is_free: false,
            price: 5.80,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Open world',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Re-Logic',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/25/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '26',
        name: 'Project Zomboid',
        priceStatus: {
            is_free: false,
            price: 10.5,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Horror',
            'Multiplayer',
            'Open world',
            'Roleplay',
            'Simulation',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'The Indie Stone',
        discountStatus: {
            discount_active: true,
            discount_amount: 33,
        },
        imageSmall: '',
        imageHeader: '../images/games/26/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '27',
        name: 'Garrys Mod',
        priceStatus: {
            is_free: false,
            price: 5.80,
        },
        categories: [
            'Arcade',
            'Multiplayer',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Facepunch Studios',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/27/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '28',
        name: 'VRChat',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Arcade',
            'Multiplayer',
            'Simulation',
            'VR',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'VRChat Inc.',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/28/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '29',
        name: 'Rocket League',
        priceStatus: {
            is_free: false,
            price: 10,
        },
        categories: [
            'Arcade',
            'Co-op',
            'Multiplayer',
            'Racing',
            'Sports',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Psyonix LLC',
        discountStatus: {
            discount_active: true,
            discount_amount: 75,
        },
        imageSmall: '',
        imageHeader: '../images/games/29/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '30',
        name: 'Total War: WARHAMMER III',
        priceStatus: {
            is_free: false,
            price: 50,
        },
        categories: [
            'Action',
            'Multiplayer',
            'RTS',
            'Singleplayer',
            'Turns',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'CREATIVE ASSEMBLY',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/30/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '31',
        name: 'Farming Simulator 22',
        priceStatus: {
            is_free: false,
            price: 20,
        },
        categories: [
            'Simulation',
            'Sandbox',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Giants Software',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/31/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '32',
        name: 'Overwatch® 2',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Arcade',
            'FPS',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Blizzard Entertainment, Inc.',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/32/headerImage.jpg',
        imageCarrousel: '',
    },
    {
        id: '33',
        name: 'Left 4 Dead 2',
        priceStatus: {
            is_free: false,
            price: 5.80,
        },
        categories: [
            'Action',
            'Co-op',
            'FPS',
            'Horror',
            'Multiplayer',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Valve',
        discountStatus: {
            discount_active: true,
            discount_amount: 90,
        },
        imageSmall: '',
        imageHeader: '../images/games/33/headerImage.jpg',
        imageCarrousel: '',
    },
];

/* console.log(steamGamesInfo); */

export { steamGamesInfo };