
let steamGamesInfo = [
    {
        id: '1',
        name: 'Counter Strike 2',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'FPS',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Valve',
        rating: '9.2/10',
        releaseDate: '21/08/2012',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/1/headerImage.jpg',
        imageCarrousel: '../images/games/1/imageCarrousel.jpg',
        imageCapsule: '../images/games/1/imageCapsule.jpg',
        description: `
            For the past two decades, Counter-Strike has provided a world-class competitive
            experience for the millions of players around the world who helped shape it.
            Now the next chapter in CS history is about to begin. We're talking about Counter-Strike 2.

            Being a free CS:GO update, Counter-Strike 2 is the most important technical advancement in the history of this franchise.
            Developed with the Source 2 engine, Counter-Strike 2 has been modernized with physics-based rendering (PBR), state-of-the-art
            networking and updated tools from the Community Workshop.
        `,
    },
    {
        id: '2',
        name: 'Baldurs Gate 3',
        priceStatus: {
            is_free: false,
            price: 35,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Singleplayer',
            'Roleplay',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Larian Studios',
        rating: '9.5/10',
        releaseDate: '03/08/2023',
        discountStatus: {
            discount_active: true,
            discount_amount: 20,
        },
        imageSmall: '',
        imageHeader: '../images/games/2/headerImage.jpg',
        imageCarrousel: '../images/games/2/imageCarrousel.jpg',
        imageCapsule: '../images/games/2/imageCapsule.jpg',
        description: `
            Gather your group and return to the Forgotten Realms in a story of companionship,
            betrayal, sacrifice, survival and the lure of absolute power.

            Mysterious abilities begin to emerge within you due to a parasite of the Azothamens implanted in your brain.
            Resist and turn darkness against itself or embrace corruption and become the ultimate evil.

            From the creators of Divinity: Original Sin 2 comes a role-playing game for the new generation of consoles,
            set in the world of Dungeons & Dragons.
        `,
    },
    {
        id: '3',
        name: 'Elden Ring',
        priceStatus: {
            is_free: false,
            price: 48,
        },
        categories: [
            'Adventure',
            'Action',
            'Fighting',
            'Singleplayer',
            'Roleplay',
            'Open world',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'FromSoftware Inc.',
        rating: '8.5/10',
        releaseDate: '24/02/2022',
        discountStatus: {
            discount_active: true,
            discount_amount: 30,
        },
        imageSmall: '',
        imageHeader: '../images/games/3/headerImage.jpg',
        imageCarrousel: '../images/games/3/imageCarrousel.jpg',
        imageCapsule: '../images/games/3/imageCapsule.jpg',
        description: `
            THE NEW FANTASY ACTION RPG.
            Rise up, blighted, and be guided by grace to wield the power of the Ring of Elden
            and become a Lord of Elden in the Midlands.

            A vast world where open fields, with a wide variety of situations, and huge dungeons, with complex,
            three-dimensional designs, connect with total fluidity. As you explore, you are accompanied by the excitement
            of discovering unknown and overwhelming threats, resulting in a great sense of accomplishment.
        
            In addition to customizing your character's appearance, you can freely combine the weapons, 
            armor and magic you wish to equip. You can develop your character according to your play style,
            such as increasing your muscular strength to become a strong warrior or mastering magic.
        `,
    },
    {
        id: '4',
        name: 'Team Fortress 2',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'FPS',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Valve',
        rating: '8.2/10',
        releaseDate: '10/10/2007',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/4/headerImage.jpg',
        imageCarrousel: '../images/games/4/imageCarrousel.jpg',
        imageCapsule: '../images/games/4/imageCapsule.jpg',
        description: '',
    },
    {
        id: '5',
        name: 'PUBG: BATTLEGROUNDS',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'KRAFTON, Inc.',
        rating: '7/10',
        releaseDate: '21/12/2017',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/5/headerImage.jpg',
        imageCarrousel: '../images/games/5/imageCarrousel.jpg',
        imageCapsule: '../images/games/5/imageCapsule.jpg',
        description: '',
    },
    {
        id: '6',
        name: 'Apex Legends',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Free to play',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Respawn',
        rating: '7.5/10',
        releaseDate: '05/11/2020',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/6/headerImage.jpg',
        imageCarrousel: '../images/games/6/imageCarrousel.jpg',
        imageCapsule: '../images/games/6/imageCapsule.jpg',
        description: '',
    },
    {
        id: '7',
        name: 'Grand Theft Auto V',
        priceStatus: {
            is_free: false,
            price: 30,
        },
        categories: [
            'Adventure',
            'Open world',
            'Singleplayer',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Rockstar North',
        rating: '8.8/10',
        releaseDate: '14/04/2015',
        discountStatus: {
            discount_active: true,
            discount_amount: 63,
        },
        imageSmall: '',
        imageHeader: '../images/games/7/headerImage.jpg',
        imageCarrousel: '../images/games/7/imageCarrousel.jpg',
        imageCapsule: '../images/games/7/imageCapsule.jpg',
        description: '',
    },
    {
        id: '8',
        name: 'Rust',
        priceStatus: {
            is_free: false,
            price: 19,
        },
        categories: [
            'Action',
            'FPS',
            'Multiplayer',
            'Open world',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Facepunch Studios',
        rating: '7/10',
        releaseDate: '08/02/2018',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/8/headerImage.jpg',
        imageCarrousel: '../images/games/8/imageCarrousel.jpg',
        imageCapsule: '../images/games/8/imageCapsule.jpg',
        description: '',
    },
    {
        id: '9',
        name: 'Stardew Valley',
        priceStatus: {
            is_free: false,
            price: 5,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'ConcernedApe',
        rating: '9.5/10',
        releaseDate: '26/02/2016',
        discountStatus: {
            discount_active: true,
            discount_amount: 40,
        },
        imageSmall: '',
        imageHeader: '../images/games/9/headerImage.jpg',
        imageCarrousel: '../images/games/9/imageCarrousel.jpg',
        imageCapsule: '../images/games/9/imageCapsule.jpg',
        description: '',
    },
    {
        id: '10',
        name: 'War Thunder',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Free to play',
            'Multiplayer',
            'Simulation',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Gaijin Entertainment',
        rating: '8/10',
        releaseDate: '15/08/2013',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/10/headerImage.jpg',
        imageCarrousel: '../images/games/10/imageCarrousel.jpg',
        imageCapsule: '../images/games/10/imageCapsule.jpg',
        description: '',
    },
    {
        id: '11',
        name: 'Palworld',
        priceStatus: {
            is_free: false,
            price: 15,
        },
        categories: [
            'Adventure',
            'Multiplayer',
            'Open world',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Pocketpair',
        rating: '6.5/10',
        releaseDate: '19/01/2024',
        discountStatus: {
            discount_active: true,
            discount_amount: 25,
        },
        imageSmall: '',
        imageHeader: '../images/games/11/headerImage.jpg',
        imageCarrousel: '../images/games/11/imageCarrousel.jpg',
        imageCapsule: '../images/games/11/imageCapsule.jpg',
        description: '',
    },
    {
        id: '12',
        name: '7 Days to Die',
        priceStatus: {
            is_free: false,
            price: 25,
        },
        categories: [
            'Action',
            'Co-op',
            'Multiplayer',
            'Horror',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'The Fun Pimps',
        rating: '7/10',
        releaseDate: '25/07/2024',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/12/headerImage.jpg',
        imageCarrousel: '../images/games/12/imageCarrousel.jpg',
        imageCapsule: '../images/games/12/imageCapsule.jpg',
        description: '',
    },
    {
        id: '13',
        name: 'Sid Meiers Civilization VI',
        priceStatus: {
            is_free: false,
            price: 48,
        },
        categories: [
            'Multiplayer',
            'Singleplayer',
            'Turns',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Firaxis Games',
        rating: '8.5/10',
        releaseDate: '21/10/2016',
        discountStatus: {
            discount_active: true,
            discount_amount: 95,
        },
        imageSmall: '',
        imageHeader: '../images/games/13/headerImage.jpg',
        imageCarrousel: '../images/games/13/imageCarrousel.jpg',
        imageCapsule: '../images/games/13/imageCapsule.jpg',
        description: '',
    },
    {
        id: '14',
        name: 'Wallpaper Engine',
        priceStatus: {
            is_free: false,
            price: 2.80,
        },
        categories: [
            'Software',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Wallpaper Engine Team',
        rating: '7/10',
        releaseDate: '15/11/2018',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/14/headerImage.jpg',
        imageCarrousel: '../images/games/14/imageCarrousel.jpg',
        imageCapsule: '../images/games/14/imageCapsule.jpg',
        description: '',
    },
    {
        id: '16',
        name: 'Dead by Daylight',
        priceStatus: {
            is_free: false,
            price: 15,
        },
        categories: [
            'Arcade',
            'Co-op',
            'Horror',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Behaviour Interactive Inc.',
        rating: '4.5/10',
        releaseDate: '14/06/2016',
        discountStatus: {
            discount_active: true,
            discount_amount: 60,
        },
        imageSmall: '',
        imageHeader: '../images/games/16/headerImage.jpg',
        imageCarrousel: '../images/games/16/imageCarrousel.jpg',
        imageCapsule: '../images/games/16/imageCapsule.jpg',
        description: '',
    },
    {
        id: '17',
        name: 'DayZ',
        priceStatus: {
            is_free: false,
            price: 50,
        },
        categories: [
            'Action',
            'Horror',
            'Multiplayer',
            'Open world',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Bohemia Interactive',
        rating: '6/10',
        releaseDate: '13/12/2018',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/17/headerImage.jpg',
        imageCarrousel: '../images/games/17/imageCarrousel.jpg',
        imageCapsule: '../images/games/17/imageCapsule.jpg',
        description: '',
    },
    {
        id: '18',
        name: 'The Sims™ 4',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Arcade',
            'Free to play',
            'Simulation',
            'Singleplayer',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'Electronic Arts',
        rating: '7.8/10',
        releaseDate: '02/11/2024',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/18/headerImage.jpg',
        imageCarrousel: '../images/games/18/imageCarrousel.jpg',
        imageCapsule: '../images/games/18/imageCapsule.jpg',
        description: '',
    },
    {
        id: '19',
        name: 'Dark and Darker',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Arcade',
            'Co-op',
            'Free to play',
            'Multiplayer',
            'Puzzle',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'IRONMACE',
        rating: '6/10',
        releaseDate: '07/06/2024',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/19/headerImage.jpg',
        imageCarrousel: '../images/games/19/imageCarrousel.jpg',
        imageCapsule: '../images/games/19/imageCapsule.jpg',
        description: '',
    },
    {
        id: '20',
        name: 'Euro Truck Simulator 2',
        priceStatus: {
            is_free: false,
            price: 10,
        },
        categories: [
            'Multiplayer',
            'Open world',
            'Simulation',
            'Singleplayer',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'SCS Software',
        rating: '7/10',
        releaseDate: '18/10/2012',
        discountStatus: {
            discount_active: true,
            discount_amount: 90,
        },
        imageSmall: '',
        imageHeader: '../images/games/20/headerImage.jpg',
        imageCarrousel: '../images/games/20/imageCarrousel.jpg',
        imageCapsule: '../images/games/20/imageCapsule.jpg',
        description: '',
    },
    {
        id: '21',
        name: 'Hearts of Iron IV',
        priceStatus: {
            is_free: false,
            price: 30,
        },
        categories: [
            'Multiplayer',
            'RTS',
            'Singleplayer',
            'Turns',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Paradox Development Studio',
        rating: '8/10',
        releaseDate: '06/06/2016',
        discountStatus: {
            discount_active: true,
            discount_amount: 70,
        },
        imageSmall: '',
        imageHeader: '../images/games/21/headerImage.jpg',
        imageCarrousel: '../images/games/21/imageCarrousel.jpg',
        imageCapsule: '../images/games/21/imageCapsule.jpg',
        description: '',
    },
    {
        id: '22',
        name: 'Fallout 4',
        priceStatus: {
            is_free: false,
            price: 12,
        },
        categories: [
            'Open world',
            'Roleplay',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Bethesda Game Studios',
        rating: '8.5/10',
        releaseDate: '10/11/2015',
        discountStatus: {
            discount_active: true,
            discount_amount: 60,
        },
        imageSmall: '',
        imageHeader: '../images/games/22/headerImage.jpg',
        imageCarrousel: '../images/games/22/imageCarrousel.jpg',
        imageCapsule: '../images/games/22/imageCapsule.jpg',
        description: '',
    },
    {
        id: '23',
        name: 'Helldivers II',
        priceStatus: {
            is_free: false,
            price: 40,
        },
        categories: [
            'Action',
            'Co-op',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Arrowhead Game Studios',
        rating: '8/10',
        releaseDate: '08/02/2024',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/23/headerImage.jpg',
        imageCarrousel: '../images/games/23/imageCarrousel.jpg',
        imageCapsule: '../images/games/23/imageCapsule.jpg',
        description: '',
    },
    {
        id: '24',
        name: 'Valheim',
        priceStatus: {
            is_free: false,
            price: 20,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Open world',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'Iron Gate AB',
        rating: '8.2/10',
        releaseDate: '02/02/2021',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/24/headerImage.jpg',
        imageCarrousel: '../images/games/24/imageCarrousel.jpg',
        imageCapsule: '../images/games/24/imageCapsule.jpg',
        description: '',
    },
    {
        id: '25',
        name: 'Terraria',
        priceStatus: {
            is_free: false,
            price: 5.80,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Multiplayer',
            'Open world',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Re-Logic',
        rating: '7.8/10',
        releaseDate: '16/05/2011',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/25/headerImage.jpg',
        imageCarrousel: '../images/games/25/imageCarrousel.jpg',
        imageCapsule: '../images/games/25/imageCapsule.jpg',
        description: '',
    },
    {
        id: '26',
        name: 'Project Zomboid',
        priceStatus: {
            is_free: false,
            price: 10.5,
        },
        categories: [
            'Adventure',
            'Co-op',
            'Horror',
            'Multiplayer',
            'Open world',
            'Roleplay',
            'Simulation',
            'Singleplayer',
            'Sandbox',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'The Indie Stone',
        rating: '8.5/10',
        releaseDate: '08/11/2013',
        discountStatus: {
            discount_active: true,
            discount_amount: 33,
        },
        imageSmall: '',
        imageHeader: '../images/games/26/headerImage.jpg',
        imageCarrousel: '../images/games/26/imageCarrousel.jpg',
        imageCapsule: '../images/games/26/imageCapsule.jpg',
        description: '',
    },
    {
        id: '27',
        name: 'Garrys Mod',
        priceStatus: {
            is_free: false,
            price: 5.80,
        },
        categories: [
            'Arcade',
            'Multiplayer',
            'Sandbox',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Facepunch Studios',
        rating: '9/10',
        releaseDate: '29/11/2006',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/27/headerImage.jpg',
        imageCarrousel: '../images/games/27/imageCarrousel.jpg',
        imageCapsule: '../images/games/27/imageCapsule.jpg',
        description: '',
    },
    {
        id: '28',
        name: 'VRChat',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Arcade',
            'Multiplayer',
            'Simulation',
            'VR',
        ],
        achievements: false,
        wishlisted: false,
        developer: 'VRChat Inc.',
        rating: '7.8/10',
        releaseDate: '01/02/2017',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/28/headerImage.jpg',
        imageCarrousel: '../images/games/28/imageCarrousel.jpg',
        imageCapsule: '../images/games/28/imageCapsule.jpg',
        description: '',
    },
    {
        id: '29',
        name: 'Rocket League',
        priceStatus: {
            is_free: false,
            price: 10,
        },
        categories: [
            'Arcade',
            'Co-op',
            'Multiplayer',
            'Racing',
            'Sports',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Psyonix LLC',
        rating: '7/10',
        releaseDate: '07/07/2015',
        discountStatus: {
            discount_active: true,
            discount_amount: 75,
        },
        imageSmall: '',
        imageHeader: '../images/games/29/headerImage.jpg',
        imageCarrousel: '../images/games/29/imageCarrousel.jpg',
        imageCapsule: '../images/games/29/imageCapsule.jpg',
        description: '',
    },
    {
        id: '30',
        name: 'Total War: WARHAMMER III',
        priceStatus: {
            is_free: false,
            price: 50,
        },
        categories: [
            'Action',
            'Multiplayer',
            'RTS',
            'Singleplayer',
            'Turns',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'CREATIVE ASSEMBLY',
        rating: '6.5/10',
        releaseDate: '17/02/2022',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/30/headerImage.jpg',
        imageCarrousel: '../images/games/30/imageCarrousel.jpg',
        imageCapsule: '../images/games/30/imageCapsule.jpg',
        description: '',
    },
    {
        id: '31',
        name: 'Farming Simulator 22',
        priceStatus: {
            is_free: false,
            price: 20,
        },
        categories: [
            'Simulation',
            'Sandbox',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Giants Software',
        rating: '7/10',
        releaseDate: '22/11/2021',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/31/headerImage.jpg',
        imageCarrousel: '../images/games/31/imageCarrousel.jpg',
        imageCapsule: '../images/games/31/imageCapsule.jpg',
        description: '',
    },
    {
        id: '32',
        name: 'Overwatch® 2',
        priceStatus: {
            is_free: true,
            price: 0,
        },
        categories: [
            'Action',
            'Arcade',
            'FPS',
            'Multiplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Blizzard Entertainment, Inc.',
        rating: '3.5/10',
        releaseDate: '10/08/2023',
        discountStatus: {
            discount_active: false,
            discount_amount: 0,
        },
        imageSmall: '',
        imageHeader: '../images/games/32/headerImage.jpg',
        imageCarrousel: '../images/games/32/imageCarrousel.jpg',
        imageCapsule: '../images/games/32/imageCapsule.jpg',
        description: '',
    },
    {
        id: '33',
        name: 'Left 4 Dead 2',
        priceStatus: {
            is_free: false,
            price: 5.80,
        },
        categories: [
            'Action',
            'Co-op',
            'FPS',
            'Horror',
            'Multiplayer',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'Valve',
        rating: '7.5/10',
        releaseDate: '17/11/2009',
        discountStatus: {
            discount_active: true,
            discount_amount: 90,
        },
        imageSmall: '',
        imageHeader: '../images/games/33/headerImage.jpg',
        imageCarrousel: '../images/games/33/imageCarrousel.jpg',
        imageCapsule: '../images/games/33/imageCapsule.jpg',
        description: '',
    },
    {
        id: '34',
        name: 'Cyberpunk 2077',
        priceStatus: {
            is_free: false,
            price: 45,
        },
        categories: [
            'Action',
            'Co-op',
            'FPS',
            'Horror',
            'Multiplayer',
            'Singleplayer',
        ],
        achievements: true,
        wishlisted: false,
        developer: 'CD Projekt Red',
        rating: '8.2/10',
        releaseDate: '9/12/2020',
        discountStatus: {
            discount_active: true,
            discount_amount: 50,
        },
        imageSmall: '',
        imageHeader: '../images/games/34/headerImage.jpg',
        imageCarrousel: '../images/games/34/imageCarrousel.jpg',
        imageCapsule: '../images/games/34/imageCapsule.jpg',
        description: '',
    },
];

/* console.log(steamGamesInfo); */

export { steamGamesInfo };